### ISSUE TITLE
Releases link on home page should go to all releases, not the latest release

### ISSUE THREAD

**Issue by dennyglee** [delta-io/website#130]
Currently the “releases” link points to the latest release of Delta Lake and it should point to the all releases (not the latest specific release).

**Comment by sibyabin** [comment]
Hi @dennyglee  ,

The url http://go.delta.io/releases  , which is currently redirecting to the latest release (https://github.com/delta-io/delta/releases/tag/v2.1.0) is referenced in 2 places.

1.  **HeroSection.jsx** 
``` <HeroLink href="http://go.delta.io/releases" newTab muted> ``` 
2.  **index.jsx**
```   url="http://go.delta.io/releases" ``` 

Cleaner approach to fix this will be:-  

(1) setup redirection from http://go.delta.io/releases   to  https://github.com/delta-io/delta/releases/
(2) Change  http://go.delta.io/releases to http://go.delta.io/latest  in **HeroSection.jsx** , 
(3) Setup redirection from http://go.delta.io/latest to https://github.com/delta-io/delta/releases/tag/v2.1.0 

Unfortunately, I could not figure out where the redirection setup is done. Is this done at the domain(CNAME) level?

Alternate approach would be to **only** change http://go.delta.io/releases to  https://github.com/delta-io/delta/releases/ in **HeroSection.jsx** , if this is fine, I'll have make this as my first commit :)

**Comment by dennyglee** [comment]
That’s a great idea; let me setup the “latest” shortly and will let you
know.  Then you can make the PR. Thanks!

**Comment by dennyglee** [comment]
Thanks @sibyabin - the go links have been updated as you have suggested:
- https://go.delta.io/releases points to https://github.com/delta-io/delta/releases/
- http://go.delta.io/latest to https://github.com/delta-io/delta/releases/tag/v2.1.0
When you get a chance, can you please create a new PR for step 2?
