### ISSUE TITLE
Add contributing to Delta Lake page to delta.io

### ISSUE THREAD

**Issue by dennyglee** [delta-io/website#141]
Currently, the Delta Lake contributing guide can be found at: https://github.com/delta-io/delta/blob/master/CONTRIBUTING.md. As Delta Lake has multiple repos, we need to create a single contributing guide that all repos can point to instead.

**Comment by sibyabin** [comment]
As per https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors , we probably can create a **.github** repo at the organization level and add the CONTRIBUTING.md in that. But the question will be does the content of the current contributing guideline covers guidelines of all the repo's in the account or not. If any specific repo's want their own customized contributing guidelines, I assume they can override by placing the same at the individual repo level

**Comment by dennyglee** [comment]
That's a good call out and worthy of discussion. The main reason for considering to put this on the website (vs. the .github repo of the org level) is because we also have other repos like delta-incubator that are outside of this specific organization but still within the same context of the Delta community.  Saying this, it is worth considering doing this and simply having all repos (and the website) point to the org contributing guide. 

As for your last point, yes, if there are individual repos that want to add more guidelines, they certainly can but it would be a superset (i.e. not an override).

**Comment by sibyabin** [comment]
PR #150  created for this

**Comment by dennyglee** [comment]
Note, keeping this issue open as we need to also update the `CONTRIBUTING.md` for the various delta-io repos.  Thanks @sibyabin for tackling the page!

**Comment by dennyglee** [comment]
Closing per https://github.com/delta-io/kafka-delta-ingest/issues/135 - thanks!
