### ISSUE TITLE
Remove warning about Glue crawler

### ISSUE THREAD

**Issue by moomindani** [delta-io/website#148]
This request is regarding this doc. https://docs.databricks.com/delta/presto-integration.html 
 "Do not use AWS Glue Crawler" 
 
In February, Glue Delta Lake crawler was launched. Currently, the above warning is not applicable. 
Is it possible for you to update this doc?

For details about Glue Delta Lake crawler, see https://aws.amazon.com/blogs/big-data/crawl-delta-lake-tables-using-aws-glue-crawlers/

@dennyglee

**Comment by dennyglee** [comment]
Thanks @moomindani - we'll work on updating the docs as soon as we can.  we've been working on updating the Delta Lake documentation and pushing them to the website so its easier for everyone to make PRs against the docs directly. Tagging @MrPowers who will be tackling this.

**Comment by dennyglee** [comment]
Thanks @moomindani - this has been updated and the docs have been fixed.  Let's work on updating Delta docs to showcase AWS glue crawler and jobs integration with Delta Lake, eh?! :)
