### ISSUE TITLE
Update "Getting Help" page

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#157]
There is a section that needs to be updated on the [Getting Help](https://delta.io/resources/getting-help) page under "Delta User Slack Channel".

The #deltalake-databricks, #delta-sharing and #deltalake-oss channels no longer exist on Slack. It is now: 
- #deltalake-questions: Discuss topics about the Delta lake open source project and its development. https://www.delta.io
- #events: Share information about Delta Lake meetups and conference talks.
- #general: All things Delta Lake.
- #random: Non-work banter and water cooler conversation.

<img width="800" alt="Screen Shot 2022-09-28 at 9 18 34 PM" src="https://user-images.githubusercontent.com/108877546/192923702-bc5066b2-34a6-4f25-97e8-88bf2cf52d09.png">

<img width="224" alt="Screen Shot 2022-09-28 at 9 19 01 PM" src="https://user-images.githubusercontent.com/108877546/192923757-04372814-adf2-47f2-9152-531254b43f2d.png">

**Comment by dennyglee** [comment]
Thanks @cakerly-lf - we will work on getting this fixed.  Thanks!

**Comment by dennyglee** [comment]
Resolved via #234 , thanks!
