### ISSUE TITLE
delta.io Top Menu Bar Social Buttons no longer work

### ISSUE THREAD

**Issue by dennyglee** [delta-io/website#160]
The delta.io StackOverflow, Twitter, LinkedIn, and Slack icons do not click even though there are `<div href="..." ...>` references. This is possible due to the recent upgrades that we need to change how the top menu bar is generated.  Note, the footer works fine.

**Comment by KaptainCS3** [comment]
!assign a can handle that

**Comment by KaptainCS3** [comment]
!assign i can handle that

**Comment by KaptainCS3** [comment]
resolve this by changing the element tag use and "<a>" instead of a div and set the href attribute

**Comment by dennyglee** [comment]
Oh sure, up for creating a PR for this?

**Comment by dennyglee** [comment]
Fixed in PR #184
