### ISSUE TITLE
Update Delta.io Banner

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#172]
The delta.io website banner is linking to the Delta 2.1.0 release. This should be updated with the most recent release, Delta 2.1.1 - https://github.com/delta-io/delta/releases/tag/v2.1.1

<img width="1112" alt="Screen Shot 2022-10-31 at 1 43 34 PM" src="https://user-images.githubusercontent.com/108877546/199074294-5e87954a-ff92-48ef-9785-2a83df798bcd.png">

@dennyglee @MrPowers

**Comment by dennyglee** [comment]
Thanks @cakerly-lf - will work on this!

**Comment by dennyglee** [comment]
This has been resolved via #174 - thanks!
