### ISSUE TITLE
Update to Social Icons in Upper Right-Hand Corner 

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#182]
Hello! Currently, the icons (Twitter, Slack, LinkedIn, etc) in the top right-hand corner of the website.

<img width="419" alt="Screen Shot 2022-11-17 at 2 29 20 PM" src="https://user-images.githubusercontent.com/108877546/202540985-f8fb7b77-43e6-4b3d-86a0-ebfbae65191d.png">

**Comment by dennyglee** [comment]
Resolved with #184 - thanks for the call out @cakerly-lf
