### ISSUE TITLE
Generate "The latest" homepage section programatically

### ISSUE THREAD

**Issue by MrPowers** [delta-io/website#192]
The delta.io homepage has the following "the latest" section:

<img width="1253" alt="Screen Shot 2022-12-08 at 12 19 52 PM" src="https://user-images.githubusercontent.com/2722395/206520348-1a08a669-1a1a-4955-908b-3a173c12aa8b.png">

Manually updating this section every time a blog post is published is a little tedious.

We should be able to grab the last 5 blog posts from listing the `src/blog` directory.  Each blog post has metadata at the top of the `index.mdx` file.  The thumbnail & title can be found from the metadata at the top of the file.  Automating this will make it easier to publish blogs.

**Comment by MrPowers** [comment]
Looks like this has been addressed?

**Comment by dev-smart-ui** [comment]
Hey @MrPowers This issue has been completed on previos milestone.
