### ISSUE TITLE
Adding Azure Stream Analytics to the service list

### ISSUE THREAD

**Issue by an-emma** [delta-io/website#218]
Hi @dennyglee,

As discussed in another issue post. We would like to have ASA added to the service list on page https://delta.io/integrations/.

Here is an example of ASA product page: https://learn.microsoft.com/en-us/azure/stream-analytics/write-to-delta-lake.

Thank you. Please let me know if you need more information.

Best,
Emma

**Comment by dennyglee** [comment]
Thanks @an-emma - will work on adding this soon, much appreciated!

**Comment by dennyglee** [comment]
Hi @an-emma - could you check https://deploy-preview-221--delta-io-beta.netlify.app/integrations to make sure it looks good?  If so, we'll merge this in - thanks! :)

**Comment by an-emma** [comment]
Thanks Denny. We do not support read yet.  

So I would just change it to "Azure Stream Analytics provides native write support of Delta Lake"

**Comment by dennyglee** [comment]
Got it!  Just updated it!  Will close this once we've merged the PR, eh?! :)

**Comment by dennyglee** [comment]
Hey @an-emma - this has been merged now so closing this issue. Please let me know if there is anything we can do to help. Much appreciated!

**Comment by an-emma** [comment]
@dennyglee what does the bold font mean? Under the product logo, there is "Azure ASA Stream Analytics". If we are referring to the full name, it is Azure Stream Analytics. Or are those just search words?

**Comment by dennyglee** [comment]
Oh yes, those are tags.  We will make those search-able though not quite yet.  Any suggestions for which search terms you'd like to use?

**Comment by an-emma** [comment]
I see. In that case what we have now is perfect. Thank you!
