### ISSUE TITLE
Update or remove roadmap

### ISSUE THREAD

**Issue by MrPowers** [delta-io/website#225]
The roadmap on the website is currently outdated: https://delta.io/roadmap

We should either update it or remove it.  Perhaps we can just make the roadmap page links to the individual project roadmaps.

**Comment by dennyglee** [comment]
Agreed that we need to update  it - with the various roadmaps that we have to address - we can update to point to the various roadmap links and/or have it link it directly to a single github issue that includes a link to all of the roadmaps.  WDYT?

**Comment by MrPowers** [comment]
This has been updated.
