### ISSUE TITLE
[community packages] DataLakeIO: Support Beam to write data to Delta Lake, and read data from Delta Lake.

### ISSUE THREAD

**Issue by zhangt-nhlab** [delta-io/website#250]
Hi, it's a pleasure to communicate again. Last year we supported Ceph storage in delta (https://github.com/delta-io/website/issues/11) , we ware grateful that you added that to delta.io/integrations. After that, we focused on the connection of Apache Beam and data lake. We noticed [beam-deltalake](https://github.com/mbenenso/beam-deltalake/), which only support users to read Delta Lake data from Beam. Because of dependency conflicts, it contains a lot of source code of [Daltalake Standalone Reader](https://github.com/delta-io/connectors/tree/master/standalone/src). 
Our [beam-datalake](https://github.com/nanhu-lab/beam-datalake) support to connect Apache Beam and data lake, such as Delta Lake, Apache Hudi, Apache iceberg. With DataLakeIO, data from Apache Beam's pipelines can be written to data lake. It is also supported to read data from data lake into Apache Beam's pipeline.
We provide test cases for beam and delta connections in [beam-delta-example](https://github.com/nanhu-lab/beam-delta-example) , there are four main steps:
* 1.The [beam-datalake](https://github.com/nanhu-lab/beam-datalake) project needs to be compiled and installed first.
* 2.Then, create a delta table using initDeltaTable(), which contains four fields: id, user_name, user_age, user_remark.
* 3.Then, use testDeltaWrite() to write the data to Delta Lake. In testDeltaWrite(), the simulated data is created, then the simulated data is converted by Apache Beam (converting the user_name to uppercase), and finally written to Delta Lake.
* 4.At last, use testDeltaRead() to read the data out of Delta Lake, and then filter according to the user_age, and write the data that meets the criteria to text.  

[beam-deltalake](https://github.com/mbenenso/beam-deltalake/) also mentioned our DataLakeIO in [issues1](https://github.com/mbenenso/beam-deltalake/issues/1), he said he wouldn't be continuing the project. So, We sincerely hope that our  [beam-datalake](https://github.com/nanhu-lab/beam-datalake) can be added to delta.io/integrations instead of his , and we will continue to optimize our features. 

Thank you very much!

**Comment by dennyglee** [comment]
Thanks very much @zhangt-nhlab  - is there a preferred logo you would like to use for this project?  This is awesome!!

**Comment by zhangt-nhlab** [comment]
> Thanks very much @zhangt-nhlab - is there a preferred logo you would like to use for this project? This is awesome!!

Hi, @dennyglee , we haven't designed a logo for this project yet, we think the Apache Beam logo is appropriate for this project on  [integrations](https://delta.io/integrations/)

**Comment by dennyglee** [comment]
thanks @zhangt-nhlab - I'll work on this ASAP!

**Comment by zhangt-nhlab** [comment]
> thanks @zhangt-nhlab - I'll work on this ASAP!

OK! Thank you so much!
