### ISSUE TITLE
Add FINOS Legend logo to delta.io/integrations

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#253]
Hello there! FINOS Legend is integrated with Delta Lake and the logo needs to be added to the Integrations section of the delta.io website - [View on GitHub here](https://github.com/finos/legend-community-delta).

Below are two different versions of the FINOS Legend logo to use. Please let me know if you have any questions! Thanks. :D

![2020_Legend_Dark](https://user-images.githubusercontent.com/108877546/229239023-c6464504-2058-4873-a520-89352234da6b.png)

![2020_Legend_Light](https://user-images.githubusercontent.com/108877546/229239046-365bc3c4-f644-4fd2-b73f-7efb27366656.png)

@dennyglee @MrPowers

**Comment by dennyglee** [comment]
Resolved with #267  - thanks!
