### ISSUE TITLE
Add April Contributor of the Month to Community Page

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#255]
Please see Tyler R. Croy's, April Contributor of the Month's (COM), write up here: https://docs.google.com/document/d/1rjnl_qbTiRFYu8kMm8YYv_4-qrNS1rYju1WHBouZnh8/edit?usp=sharing

Headshot: https://www.databricks.com/dataaisummit/speaker/r-tyler-croy

Please add this to the [Community Page](https://delta.io/community) and replace [last month's COM](https://delta.io/profiles/gerhard-brueckl) with Tyler's write-up.

Thank you!

@dennyglee @MrPowers

**Comment by dennyglee** [comment]
Thanks @cakerly-lf  - we'll target this to be a May contributor of the month - my bad on the delay.  Thanks!
