### ISSUE TITLE
Not Secure Error - certificate expired on Wednesday, April 5, 2023 at 4:59:59 PM

### ISSUE THREAD

**Issue by JHibbard** [delta-io/website#259]
![Screen Shot 2023-04-05 at 11 33 30 PM](https://user-images.githubusercontent.com/8717652/230290994-6d14f54c-d955-47b0-bb0a-c77f975e5c7b.png)

**Comment by dennyglee** [comment]
Thanks @JHibbard - we have fixed this certificate error.
