### ISSUE TITLE
Delta Sharing Page - Outdated or Confusing Information

### ISSUE THREAD

**Issue by JHibbard** [delta-io/website#261]
On the [delta sharing page](https://delta.io/sharing) towards the bottom, there's a "Connecting to Delta Sharing" section with a "and more are coming soon!" area indicating that presto, trino, rust, hive, and Tableau aren't supported yet. Further down the page, these clients are listed as having open source clients.

![Screen Shot 2023-04-06 at 2 15 40 AM](https://user-images.githubusercontent.com/8717652/230333433-abf0e713-95c4-4548-9512-1ad1c0017571.png)

**Comment by MrPowers** [comment]
Can you please provide more specific instructions on the changes that should be made to this page?

**Comment by dennyglee** [comment]
Let's remove the "and more are coming soon!" section and the associated logos
