### ISSUE TITLE
Add LF Projects banner to delta.io website

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#265]
This LF Projects banner should be added to the top of the delta.io website. The Linux Foundation project websites use this banner to show that they are part of The Linux Foundation. 

![lfprojects_banner_other](https://user-images.githubusercontent.com/108877546/230511153-d7f85e59-c69c-4120-a0f4-d40c8e5acd1c.svg)

Thank you! @dennyglee @MrPowers

**Comment by dennyglee** [comment]
To provide context, can we add the black bar of Linux Foundation Projects similar to the one seen here: https://lfaidata.foundation/blog/2022/09/12/feathr-joins-lf-ai-data-as-new-sandbox-project/
