### ISSUE TITLE
New Google Analytics ID for linen.dev - Tag needs to be added across all pages

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#274]
A new Google Analytics ID was generated for for linen.dev. Please add the following tag across all pages on the site after the <head> element:

 <script async src="https://www.googletagmanager.com/gtag/js?id=G-NKMW5Q1XJZ"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-NKMW5Q1XJZ'); </script>

Thank you!
@MrPowers @dennyglee

**Comment by dennyglee** [comment]
Thanks @cakerly-lf  - I've updated linen so let's see if this does the trick.  thanks!
