### ISSUE TITLE
Update user logos to link to corresponding user stories

### ISSUE THREAD

**Issue by MrPowers** [delta-io/website#278]
The user logos are currently in a single image:

<img width="1318" alt="Screenshot 2023-05-04 at 6 22 39 PM" src="https://user-images.githubusercontent.com/2722395/236342419-83ef8a6a-49cb-412f-b003-3419021fedb9.png">

We'd like to break up this image into separate icons.  The icons that link to a user story should route to the correct page.  Logos that don't have an associated user story shouldn't link anywhere.

For example, the Scribd logo should link to [this page](https://delta.io/user-stories/scribd/). 

We should save the images in some directory that allows us to easily change the order.  There should be an intelligent filenaming convention.  e.g. scribd.png should link to user-stories/scribd.

**Comment by dennyglee** [comment]
Please also add the Kubit logo (no user story yet but we should add them)
![kubit-logo-white-on-blue-stacked](https://user-images.githubusercontent.com/1446829/236603201-e0cebf98-8854-457c-a5ef-13abeafeaf5c.png)
