### ISSUE TITLE
Update Delta Sharing Ecosystem with new logos 

### ISSUE THREAD

**Issue by dennyglee** [delta-io/website#298]
New partners within Delta ecosystem like Cloudflare, Twilio, Oracle, and Dell were just announced today. Should update the delta.io/sharing page with the new splash.

**Comment by dennyglee** [comment]
<img width="2532" alt="delta-sharing-ecosystem" src="https://github.com/delta-io/website/assets/1446829/73e26596-073d-416d-8d23-da759e0ef092">

**Comment by dev-smart-ui** [comment]
Hey @dennyglee! Could you elaborate on the mobile version of this image? We need this image to be vertical for mobile devices. Do we need to do it ourselves or do you have such a picture?
