### ISSUE TITLE
LinkedIn links at the bottom of blog post are appearing twice

### ISSUE THREAD

**Issue by djliden** [delta-io/website#313]
This shows up in both Firefox and Chrome; e.g. on https://delta.io/blog/2022-10-15-version-pandas-dataset/

<img width="258" alt="image" src="https://github.com/delta-io/website/assets/7102904/04d21823-fad7-4fb8-afbd-9d7be50672b9">

**Comment by nkarpov** [comment]
fixed with updated profile images
