### ISSUE TITLE
Remove mentions to the archived `connectors` repo

### ISSUE THREAD

**Issue by manuteleco** [delta-io/website#324]
The [connectors](https://github.com/delta-io/connectors) repository has been recently archived (on Jul 13, 2023). Its contents have been moved into the [delta](https://github.com/delta-io/delta) repository, under `connectors`.

Therefore, the website should not include explicit mentions or calls for contributions to the archived `connectors` repository anymore.

The repository is currently listed in the _Community_ and _Roadmap_ pages.

**Comment by dennyglee** [comment]
Thanks @manuteleco - appreciate you tackling this.  reviewing this now!
