### ISSUE TITLE
Update links to the archived `connectors` repo

### ISSUE THREAD

**Issue by manuteleco** [delta-io/website#326]
The [connectors](https://github.com/delta-io/connectors) repository has been recently archived (on Jul 13, 2023). Its contents have been moved into the [delta](https://github.com/delta-io/delta) repository, under connectors.

Therefore, any link pointing to the archived repository should be updated to point to the new location instead.

**Comment by dennyglee** [comment]
Thanks @manuteleco - appreciate you doing this.  will review shortly!
