### ISSUE TITLE
Slack link no longer active

### ISSUE THREAD

**Issue by cakerly-lf** [delta-io/website#342]
Hi there! The URL to join the Delta Users Slack, https://go.delta.io/slack, is no longer active. See screenshot below:

![1695751277382-1](https://github.com/delta-io/website/assets/108877546/d859151f-89a3-4f54-a417-80df4d612621)

**Comment by cakerly-lf** [comment]
@MrPowers @dennyglee

**Comment by dennyglee** [comment]
Thanks @cakerly-lf  - could you check now?  Much appreciated!

**Comment by cakerly-lf** [comment]
It is now working! Thank you very much.

Carly

**Comment by MrPowers** [comment]
Duplicate: https://github.com/delta-io/website/issues/310

**Comment by MrPowers** [comment]
This is broken again

**Comment by dennyglee** [comment]
thanks for the reminder @MrPowers  - could you check to see if this works now?

**Comment by monometa** [comment]
@dennyglee Hi, it seems that the link is broken now and I am getting the message "This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link." Could you please update it once again?

**Comment by dennyglee** [comment]
Thanks @cakerly-lf  - I just updated the bit.ly link - could you validate when you get the chance?  Thanks!

**Comment by jengdal** [comment]
The link has expired again.
