### ISSUE TITLE
Blog post proposal: repartition Delta Table (with generated partition column)

### ISSUE THREAD

**Issue by keen85** [delta-io/website#387]
I use a Delta table to store large amounts of transactional data. Initially I decided to partition it by year of the transaction; using a generated column (generation expression=`DATE_TRUNC('YEAR', transaction_timestamp)`) as partitioning column.

However, it turned out, that year partitions are too coarse grained, so I'd wanted to change the granularity from year to month.

I did not find any documentation on this but finally found a way to do it (unfortunately requiring complete rewrite of the table) but from an end-user perspective still quite simple.

I'd like to write a blog post on this use case and highlight the consequences (rewrite of table), benefits (potentially faster reads due to partition pruning) and other interesting stuff that I came by. 

@MrPowers or @dennyglee do you think that this a good topic for a blog post? Would any of you be willing to review my draft (when it is done)?

**Comment by MrPowers** [comment]
@keen85 - yea, sounds like an interesting post, but think Liquid is the real solution here.  Did you try Liquid?

**Comment by keen85** [comment]
@MrPowers yes, Liquid Clustering _will be_ the better solution, making things much easier _in future_.
But in Delta OSS 3.1 Liquid it is still "in preview"; I think it will be "production ready" in Delta 3.2 (https://github.com/delta-io/delta/issues/1874).

I'm on Azure Synapse / Microsoft Fabric; stuck with [Delta 2.2](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-33-runtime) ([soon 2.4](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-34-runtime)) for some more time 😕.

So, I think a blog post might be helpful nonetheless for Delta users who still use hive-style partitioning and who face the same issue in production _now_.

**Comment by keen85** [comment]
@MrPowers this is my first draft for the blog post:
https://github.com/keen85/delta-io-website/blob/blog/387_partition_evolution/src/blog/2024-04-xx-partition-evolution/index.mdx

Should I create a pull request so you can add some comments?

**Comment by MrPowers** [comment]
@keen85 - draft looks good.

Would you be OK just adding those sections to this post on the [pros & cons of Hive-style partitioning](https://delta.io/blog/pros-cons-hive-style-partionining/)?

Would be happy to add you as a co-author of course!

**Comment by keen85** [comment]
@MrPowers, sure; I'll try to incorporate it there.
