### ISSUE TITLE
We need some proof letters about our contribution to the Delta Lake community

### ISSUE THREAD

**Issue by zhangt-nhlab** [delta-io/website#463]
Hello!

We (Nanhu Laboratory) have been using Delta Lake for several years and have witnessed its growth during these years. During this period, Zhang Tao has developed an open-source connector called Beam Delta Lake. With that, data from Apache Beam's pipelines can be read from and written to Delta Lake. Wang Peng has developed an open-source connector between Delta Lake and Ceph. This connector allows users to read and write from Delta tables on Ceph. Both connectors have been open sourced and contributed to the community module of Delta Lake's Integrations page.
![图片3](https://github.com/user-attachments/assets/77a8a32e-c317-4bd5-8d72-3a1363615421)
At present, we (Nanhu Laboratory) need proof materials. Can you send official proof letters separately to zhangtao@nanhulab.ac.cn and wp@nanhulab.ac.cn ? I am looking forward to your letter very much.

-------------------------------------------------------------------------------------------------------------------------
Here is a simple sample email sent to zhangtao@nanhulab.ac.cn

Nanhu Laboratory:

Thank you for your attention to Delta Lake! Zhang Tao from your laboratory has developed the open-source connector named Beam Delta Lake. With this connector, data from Apache Beam's pipelines can be read from and written to Delta Lake. It's a great connector! This connector has been integrated into the community module of Delta Lake's Integrations page. Thank you for your contributions.
![图片1](https://github.com/user-attachments/assets/85e387ee-5bd1-4e6a-a2ef-b4b5433e9af6)

Thank you sincerely!

-------------------------------------------------------------------------------------------------------------------------

Here is a simple sample email sent to wp@nanhulab.ac.cn

Nanhu Laboratory:

Thank you for your attention to Delta Lake! Wang Peng from your laboratory has developed an open-source connector between Delta Lake and Ceph. This connector allows users to read and write from Delta tables on Ceph. It's a great connector! This connector has been integrated into the community module of Delta Lake's Integrations page. Thank you for your contributions.
![图片2](https://github.com/user-attachments/assets/27fb2b6a-84ff-4b9e-a696-a8000c087c31)

Thank you sincerely!

**Comment by dennyglee** [comment]
Thanks @zhangt-nhlab  - I will get back to you soon on this - much appreciated!
