### ISSUE TITLE
https://delta.io/docs/ should point to the docs and not the intermediate page

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/website#52]
Currently `https://delta.io/docs/` points to a landing page. The actual docs (https://docs.delta.io/latest/index.html) are available once you click on the "Docs" link in page `https://delta.io/docs/`.

I think https://delta.io/docs/ should point directly to the actual docs (https://docs.delta.io/latest/index.html)

**Comment by jodb** [comment]
@vkorukanti I think this may be taken care of now with the new way the top-level navigation on Delta.io works. When you click on "Docs" at the top level, it takes you directly to https://docs.delta.io/latest/index.html via https://docs.delta.io. Does this now work in the manner that you would expect? 

https://delta.io/docs/ still exists as an extra page but I will put a PR in to remove it separately and it currently isn't referenced from anywhere on the website.

Let me know if it is currently working in the manner you expect or if we need to discuss this issue further.

Thanks!

**Comment by vkorukanti** [comment]
@jodb It looks good now, thank you for fixing this.

**Comment by jodb** [comment]
No worries but this one was TD, I'm just the messenger:)
